services:
  - type: web
    name: tweet-app
    env: python
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn chaiheadq.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chaiheadq.settings
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: tweet-db
          property: connectionString
    autoDeploy: true

databases:
  - name: tweet-db
    plan: free
